name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Copy model files
      run: |
        mkdir -p models
        cp models/best_model.pkl
        cp models/scaler.pkl 

    - name: Run data tests
      run: |
        pytest -s tests/test_data.py

    - name: Balance the dataset
      run: |
        python scripts/balance_data.py

    - name: Train the model
      run: |
        python scripts/model_comparison.py

    - name: Run training tests
      run: |
        pytest -s tests/test_training.py

    - name: Run explainability tests
      run: |
        pytest -s tests/test_explainability.py

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Copy model files
      run: |
        mkdir -p models
        cp models/best_model.pkl 
        cp models/scaler.pkl

    - name: Deploy application
      run: |
        python app.py
